// JS Object containing speaker names, life events, and associated dates
var eventsData = [
  {name: "Aaron",
  lifespan_start: "116 B.C.",
  lifespan_end: "59 B.C.",
  events: [{year: "116 B.C. *", description: "Aaron is born."},
   {year: "100-92 B.C.", description: "Aaron sees an angel and is converted to the faith."},
   {year: "90-77 B.C.", description: "Aaron and his brothers go on missions to the Lamanites."},
   {year: "88 B.C. *", description: "Aaron teaches Lamoni's father the gospel."},
   {year: "59 B.C. *", description: "Aaron dies."}]},
 {name: "Abinadi",
  lifespan_start: "199 B.C.",
  lifespan_end: "148 B.C.",
  events: [{year: "199 B.C. *", description: "Abinadi is born."},
   {year: "150 B.C.", description: "Abinadi cries repentance to the people of King Noah, but the people try to kill him."},
   {year: "148 B.C.", description: "Abinadi returns and prophesies in disguise, but is captured by the people."},
   {year: "148 B.C.", description: "Abinadi is executed by King Noah and his priests."}]},
 {name: "Abinadom",
  lifespan_start: "274 B.C.",
  lifespan_end: "179 B.C.",
  events: [{year: "274 B.C. *", description: "Abinadom is born."},
   {year: "219 B.C. *", description: "Abinadom gets the plates from Chemish."},
   {year: "179 B.C. *", description: "Abinadom gives the small plates to Amaleki and dies."}]},
 {name: "Alma",
  lifespan_start: "173 B.C.",
  lifespan_end: "91 B.C.",
  events: [{year: "173 B.C.", description: "Alma is born."},
   {year: "148 B.C.", description: "Alma is converted through Abinadi's teachings, pleads for Abinadi's life, and flees from the king's servants."},
   {year: "147-145 B.C.", description: "Alma teaches the people privately. They gather at the waters of Mormon and are baptized. Alma founds a church."},
   {year: "145 B.C. *", description: "Alma and his people flee from King Noah's army."},
   {year: "145-121 B.C.", description: "Alma and his people establish the city of Helam. They are conquered by Lamanites."},
   {year: "120 B.C.", description: "Alma and his people flee from Helam and arrive at Zarahemla. King Mosiah authorizes Alma to organize the Church of God. Alma is high priest of the Church."},
   {year: "100-92 B.C.", description: "Alma's rebellious son sees an angel and is converted because of Alma's prayers."},
   {year: "91 B.C.", description: "Alma dies."}]},
 {name: "Alma2",
  lifespan_start: "124 B.C.",
  lifespan_end: "73 B.C.",
  events: [{year: "124 B.C. *", description: "Alma is born."},
   {year: "120 B.C. *", description: "Alma's father leads the people of Helam to Zarahemla."},
   {year: "100-92 B.C.", description: "Alma is converted to the gospel after an angelic visitation, and he and the sons of Mosiah declare glad tidings."},
   {year: "91 B.C.", description: "Alma is appointed as the first chief judge over the people and high priest over the Church."},
   {year: "83 B.C.", description: "Alma delivers up the judgment seat to Nephihah to devote his time entirely to the ministry. He preaches in Zarahemla, Gideon, and Melek."},
   {year: "82 B.C.", description: "Alma is rejected in Ammonihah, commanded to return, and joined by Amulek. They contend with Zeezrom, witness the martyrdom of the believers, and are imprisoned."},
   {year: "81 B.C.", description: "Alma and Amulek are miraculously delivered from prison in Ammonihah. They preach in Sidom."},
   {year: "74 B.C.", description: "Alma confounds Korihor. He leads a mission to the Zoramites and gives the records to Helaman."},
   {year: "73 B.C.", description: "Alma leaves for Melek and is never seen again. He is believed to be taken up by the Spirit."}]},
 {name: "Amaleki",
  lifespan_start: "209 B.C.",
  lifespan_end: "128 B.C.",
  events: [{year: "209 B.C. *", description: "Amaleki is born."},
   {year: "199 B.C. *", description: "Amaleki's brother joins Zeniff's expedition, and Amaleki never sees him again."},
   {year: "179 B.C. *", description: "Amaleki receives the small plates."},
   {year: "129 B.C. *", description: "Amaleki writes the final entry in the Small Plates of Nephi and gives them to King Benjamin."},
   {year: "128 B.C. *", description: "Amaleki dies."}]},
 {name: "Amalickiah",
  lifespan_start: "102 B.C.",
  lifespan_end: "65 B.C.",
  events: [{year: "102 B.C. *", description: "Amalickiah is born."},
	  {year: "72 B.C.", description: "Amalickiah conspires to be king of the Lamanites and incites war against the Nephites."},
   {year: "65 B.C.", description: "Amalickiah is killed by Teancum."}]},
 {name: "Amaron",
  lifespan_start: "324 B.C.",
  lifespan_end: "279 B.C.",
  events: [{year: "324 B.C. *", description: "Amaron is born."},
   {year: "279 B.C.", description: "Amaron writes in the small plates and passes them to his brother Chemish."},
   {year: "279 B.C. *", description: "Amaron dies."}]},
 {name: "Aminadab",
  lifespan_start: "54 B.C.",
  lifespan_end: "A.D. 6",
  events: [{year: "54 B.C. *", description: "Aminadab is born."},
	  {year: "29 B.C.", description: "While the brothers Nephi and Lehi are imprisoned, Aminadab is brought back to the faith. He preaches faith and repentance to the Lamanite guards."},
	{year: "A.D. 6 *", description: "Aminadab dies."}]},
 {name: "Ammaron",
  lifespan_start: "A.D. 270",
  lifespan_end: "A.D. 322",
  events: [{year: "A.D. 270 *", description: "Ammaron is born."},
	  {year: "A.D. 321", description: "Ammaron hides up all the sacred records."},
   {year: "A.D. 322", description: "Ammaron instructs 10-year-old Mormon about the records."},
   {year: "A.D. 322", description: "Ammaron dies"}]},
 {name: "Ammon",
  lifespan_start: "119 B.C.",
  lifespan_end: "59 B.C.",
  events: [{year: "119 B.C. *", description: "Ammon is born."},
   {year: "100-92 B.C.", description: "Ammon is converted to the gospel after an angelic visitation."},
   {year: "90 B.C.", description: "Ammon leads a mission to the Lamanites."},
   {year: "89 B.C. *", description: "Ammon teaches King Lamoni and his household the gospel, baptizes many, and establishes a church in the land of Ishmael. He goes to Middoni to rescue Aaron and his brothers and fights Lamoni's father."},
   {year: "77 B.C.", description: "Ammon and his brethren return to Zarahemla with the people of Anti-Nephi-Lehi."},
   {year: "73 B.C.", description: "Ammon accompanies Alma the Younger on a mission to the Zoramites."},
   {year: "71 B.C.", description: "Ammon preaches among the people."},
   {year: "59 B.C. *", description: "Ammon dies."}]},
 {name: "Ammon2",
  lifespan_start: "154 B.C.",
  lifespan_end: "74 B.C.",
  events: [{year: "154 B.C. *", description: "Ammon is born."},
	  {year: "121 B.C.", description: "Ammon leads 16 men to Zarahemla."},
   {year: "121 B.C.", description: "Ammon discovers the people of Limhi and leads them into the land of Zarahemla under Mosiah the First's reign."},
  	{year: "74 B.C. *", description: "Ammon dies."}]},
 {name: "Ammoron",
  lifespan_start: "105 B.C.",
  lifespan_end: "60 B.C.",
  events: [{year: "105 B.C. *", description: "Ammoron is born."},
	  {year: "65 B.C.", description: "Ammoron succeeds Amalickiah as king of the Lamanites."},
   {year: "63 B.C.", description: "Ammoron and Moroni negotiate a prisoner exchange."},
   {year: "60 B.C.", description: "Ammoron is killed by Teancum."}]},
 {name: "Amulek",
  lifespan_start: "129 B.C.",
  lifespan_end: "59 B.C.",
  events: [{year: "129 B.C. *", description: "Amulek is born."},
   {year: "82 B.C.", description: "Amulek meets Alma and they preach together in Ammonihah."},
   {year: "81 B.C.", description: "Alma and Amulek are miraculously delivered from prison in Ammonihah and preach in Sidom."},
   {year: "74 B.C.", description: "Amulek accompanies Alma as his companion on a mission to the Zoramites."},
   {year: "59 B.C. *", description: "Amulek dies."}]},
 {name: "AntiNephiLehi",
  lifespan_start: "139 B.C.",
  lifespan_end: "64 B.C.",
  events: [{year: "139 B.C. *", description: "Anti-Nephi-Lehi is born."},
   {year: "86 B.C. *", description: "Anti-Nephi-Lehi is converted to the gospel of Jesus Christ."},
   {year: "80 B.C. *", description: "Anti-Nephi-Lehi is made king over all the Lamanites. The non-converted Lamanites attack the people of Anti-Nephi-Lehi, who do not resist them."},
   {year: "77 B.C.", description: "The sons of Mosiah lead the people of Anti-Nephi-Lehi to the land of Zarahemla."},
   {year: "64 B.C. *", description: "Anti-Nephi-Lehi dies."}]},
 {name: "Antionah",
  lifespan_start: "116 B.C.",
  lifespan_end: "41 B.C.",
  events: [{year: "116 B.C. *", description: "Antionah is born."},
	  {year: "82 B.C.", description: "Antionah asks Alma and Amulek a question about resurrection."},
  	{year: "41 B.C. *", description: "Antionah dies."}]},
 {name: "Benjamin",
  lifespan_start: "184 B.C.",
  lifespan_end: "121 B.C.",
  events: [{year: "184 B.C. *", description: "Benjamin is born."},
   {year: "129 B.C. *", description: "Benjamin wields the Sword of Laban in battle against the Lamanites."},
   {year: "124 B.C.", description: "Benjamin delivers his sermon from the temple and consecrates Mosiah to be king over the Nephites."},
   {year: "121 B.C.", description: "Benjamin dies."}]},
 {name: "BrothersNephi",
  lifespan_start: "619 B.C.",
  lifespan_end: "544 B.C.",
  events: [{year: "619-610 B.C. *", description: "Nephi's brethren are born."},
   {year: "597 B.C.", description: "Lehi's family departs into the wilderness."},
   {year: "596-588 B.C.", description: "Nephi and his brothers return to Jerusalem for the brass plates, and then again for Ishmael's family. They marry Ishmael's daughters, murmur repeatedly, and are in turn chastened repeatedly."},
   {year: "588 B.C.", description: "Lehi's family arrives in the land Bountiful, and Laman and Lemuel attempt to sabotage Nephi's efforts to build a ship. After the ship is complete, they set sail for the promised land."},
   {year: "587-586 B.C.", description: "Lehi's family arrives in the promised land after Laman and Lemuel bind Nephi and steer the ship into a tempest."},
   {year: "585 B.C. *", description: "Nephi and his brothers receive their final blessings from Lehi."},
   {year: "584 B.C. *", description: "Lehi dies. Nephi, Sam, and Nephi's followers separate from Laman and Lemuel."},
   {year: "544 B.C. *", description: "Nephi's brethren have died."}]},
 {name: "CaptainMoroni",
  lifespan_start: "99 B.C.",
  lifespan_end: "56 B.C.",
  events: [{year: "99 B.C.", description: "Moroni is born."},
   {year: "74 B.C.", description: "Moroni and Lehi defeat the army of Zerahemnah."},
   {year: "73 B.C.", description: "Moroni raises the title of liberty to rally the people against Amalickiah and prepares them for war."},
   {year: "67 B.C.", description: "Moroni suppresses the king-men. Amalickiah takes several Nephite cities."},
   {year: "61 B.C.", description: "Moroni and Pahoran suppress a rebellion in the land of Zarahemla led by Pachus."},
   {year: "60 B.C.", description: "Moroni drives the Lamanite armies out of the land of the Nephites, ending the war. "},
   {year: "59 B.C.", description: "Moroni places his son Moronihah in charge of the Nephite armies and retires."},
   {year: "56 B.C.", description: "Moroni dies."}]},
 {name: "Chemish",
  lifespan_start: "324 B.C.",
  lifespan_end: "249 B.C.",
  events: [{year: "324 B.C. *", description: "Chemish is born."},
   {year: "279 B.C.", description: "Chemish receives the small plates from Amaron."},
   {year: "249 B.C. *", description: "Chemish dies."}]},
 {name: "Christ",
  lifespan_start: "A.D. 1",
  lifespan_end: "A.D. 35",
  events: [{year: "A.D. 1", description: "Christ is born."},
   {year: "A.D. 13", description: "Christ teaches in the temple at 12 years old."},
   {year: "A.D. 31", description: "Christ is baptized and begins His ministry in the Old World."},
   {year: "A.D. 34", description: "Christ is crucified, resurrected, and appears to the Nephites."}]},
 {name: "Enos",
  lifespan_start: "515 B.C.",
  lifespan_end: "417 B.C.",
  events: [{year: "515 B.C. *", description: "Enos is born."},
   {year: "494 B.C. *", description: "Enos receives the small plates."},
   {year: "495-450 B.C. *", description: "Enos prays to the Lord on behalf of himself, the Nephites, and the Lamanites."},
   {year: "449-418 B.C. *", description: "Enos records his story, having spent years preaching to the Nephites."},
   {year: "418 B.C. *", description: "Enos gives the plates to his son, Jarom."},
   {year: "417 B.C. *", description: "Enos dies."}]},
 {name: "Ether",
  lifespan_start: "639 B.C.",
  lifespan_end: "569 B.C.",
  events: [{year: "639 B.C. *", description: "Ether is born"},
   {year: "569 B.C. *", description: "Ether sees the end of the Jaredite nation, finishes his record, and dies"}]},
 {name: "FatherLamoni",
  lifespan_start: "149 B.C.",
  lifespan_end: "80 B.C.",
  events: [{year: "149 B.C. *", description: "Lamoni's father is born."},
	  {year: "90 B.C.", description: "Lamoni's father meets and fights Ammon, and releases Ammon's brothers from prison."},
   {year: "88 B.C. *", description: "Aaron teaches Lamoni's father the gospel, and he is converted."},
   {year: "80 B.C. *", description: "Lamoni's father confers the kingdom on his son, Anti-Nephi-Lehi, and dies."}]},
 {name: "Gid",
  lifespan_start: "92 B.C.",
  lifespan_end: "7 B.C.",
  events: [{year: "92 B.C. *", description: "Gid is born."},
	  {year: "63 B.C.", description: "Gid, Helaman, and Teomner retake the city of Manti. Gid reports the rebellion, slaying, and escape of some Lamanite prisoners."},
	  {year: "7 B.C. *", description: "Gid dies."}]},
 {name: "Giddianhi",
  lifespan_start: "37 B.C.",
  lifespan_end: "A.D. 19",
  events: [{year: "37 B.C. *", description: "Giddianhi is born."},
	  {year: "A.D. 16", description: "Giddianhi, the leader of the Gadianton robbers, sends a message to Lachoneus, the governor of the Nephites, demanding that he surrender or be destroyed."},
   {year: "A.D. 18", description: "Giddianhi and the robbers take possession of the lands deserted by the Nephites."},
   {year: "A.D. 19", description: "Giddianhi and the robbers attack the Nephites. A great and terrible battle ensues. Giddianhi is slain."}]},
 {name: "Giddonah",
  lifespan_start: "124 B.C.",
  lifespan_end: "44 B.C.",
  events: [{year: "124 B.C. *", description: "Giddonah is born."},
	  {year: "74 B.C.", description: "Giddonah, the high priest of the land of Gideon, questions Korihor, the Anti-Christ."},
	  {year: "44 B.C. *", description: "Giddonah dies."}]},
 {name: "Gideon",
  lifespan_start: "190 B.C.",
  lifespan_end: "90 B.C.",
  events: [{year: "190 B.C. *", description: "Gideon is born."},
	  {year: "145 B.C.", description: "Gideon tries to kill King Noah."},
   {year: "133 B.C. *", description: "Gideon helps prevent war over the abducted Lamanite women."},
   {year: "120 B.C. *", description: "Gideon helps the people of Limhi escape from bondage."},
   {year: "91 B.C.", description: "Gideon is killed by Nehor."}]},
 {name: "Gidgiddoni",
  lifespan_start: "13 B.C.",
  lifespan_end: "A.D. 41",
  events: [{year: "13 B.C. *", description: "Gidgiddoni is born."},
	  {year: "A.D. 17", description: "Gidgiddoni is appointed chief captain of the Nephite armies. He refuses to attack the Gadianton robbers."},
   {year: "A.D. 19", description: "Gidgiddoni repels the first attack of the Gadianton robbers."},
   {year: "A.D. 22", description: "Gidgiddoni and his armies defeat the Gadianton robbers."},
	  {year: "A.D. 41*", description: "Gidgiddoni dies."}]},
 {name: "Helaman",
  lifespan_start: "120 B.C.",
  lifespan_end: "57 B.C.",
  events: [{year: "120 B.C.", description: "Helaman's grandfather, Alma, leads the people of Helam to Zarahemla after being miraculously delivered from bondage."},
   {year: "100-92 B.C.", description: "Helaman's father, Alma the younger, is converted to the gospel after an angelic visitation."},
   {year: "89 B.C. *", description: "Helaman is born."},
   {year: "73 B.C.", description: "Alma the Younger instructs Helaman and entrusts him with the sacred Nephite records."},
   {year: "63 B.C.", description: "Helaman leads the 2,000 stripling warriors against the armies of Ammoron in the west."},
   {year: "63 B.C.", description: "Helaman successfully retakes the city of Manti. The Lamanite armies flee out of that quarter of the land."},
   {year: "57 B.C.", description: "Helaman dies."}]},
 {name: "Helaman2",
  lifespan_start: "74 B.C.",
  lifespan_end: "39 B.C.",
  events: [{year: "74 B.C. *", description: "Helaman is born."},
   {year: "53 B.C.", description: "Helaman receives the sacred records from his uncle, Shiblon."},
   {year: "50 B.C.", description: "Helaman is appointed to fill the judgment-seat."},
   {year: "39 B.C.", description: "Helaman dies."}]},
 {name: "Jacob",
  lifespan_start: "594 B.C.",
  lifespan_end: "495 B.C.",
  events: [{year: "594 B.C. *", description: "Jacob is born."},
   {year: "587 B.C.", description: "Jacob suffers afflictions because of Laman and Lemuel's rebellion on the ocean."},
   {year: "585 B.C. *", description: "Jacob and his brothers receive their final blessings from Lehi."},
   {year: "584 B.C. *", description: "Lehi dies. Jacob, Nephi, and others separate from Laman and Lemuel."},
   {year: "569 B.C.", description: "Nephi consecrates Jacob as a priest."},
   {year: "559 B.C.", description: "Jacob and Nephi speak to the Nephites."},
   {year: "554 B.C. *", description: "Jacob learns that the Messiah's name will be Christ."},
   {year: "544 B.C.", description: "Nephi gives the small plates to Jacob. Jacob and Joseph try to persuade the Nephites to believe in Christ and keep His commandments."},
   {year: "529 B.C. *", description: "Jacob contends with Sherem the anti-Christ."},
   {year: "509 B.C. *", description: "Jacob gives Enos the small plates. "},
   {year: "495 B.C. *", description: "Jacob dies."}]},
 {name: "Jarom",
  lifespan_start: "439 B.C.",
  lifespan_end: "359 B.C.",
  events: [{year: "439 B.C. *", description: "Jarom is born."},
   {year: "422 B.C. *", description: "Jarom is given the small plates by his father, Enos."},
   {year: "399 B.C. *", description: "The Nephites prosper in the land and are victorious over the Lamanites."},
   {year: "360 B.C. *", description: "Jarom gives the small plates to his son, Omni."},
   {year: "359 B.C. *", description: "Jarom dies."}]},
 {name: "JohnBaptist",
  lifespan_start: "A.D. 1",
  lifespan_end: "A.D. 33",
  events: [{year: "A.D. 1", description: "John the Baptist is born."},
   {year: "A.D. 31", description: "John baptizes Jesus prior to His ministry."},
   {year: "A.D. 32", description: "John the Baptist is imprisoned for criticizing Herod's unlawful marriage to his brother's wife."},
   {year: "A.D. 33", description: "John is beheaded."}]},
 {name: "Korihor",
  lifespan_start: "109 B.C.",
  lifespan_end: "74 B.C.",
  events: [{year: "109 B.C. *", description: "Korihor is born."},
   {year: "91 B.C.", description: "Alma the Younger is appointed as the first chief judge of the reign of the judges."},
   {year: "83 B.C.", description: "Alma the Younger gives up his position as chief judge to devote his time entirely to the ministry."},
   {year: "74 B.C.", description: "Korihor preaches against Christ, is struck dumb by Alma the Younger, and is killed by the Zoramites."}]},
 {name: "Laban",
  lifespan_start: "650 B.C.",
  lifespan_end: "599 B.C.",
  events: [{year: "650 B.C. *", description: "Laban is born."},
	  {year: "599 B.C. *", description: "Laban threatens to kill Laman and his brothers when they try to get the brass plates from him. Later, Nephi kills him and steals the brass plates."}]},
 {name: "Lachoneus",
  lifespan_start: "16 B.C.",
  lifespan_end: "A.D. 31",
  events: [{year: "16 B.C. *", description: "Lachoneus is born."},
	  {year: "A.D. 1", description: "Lachoneus becomes chief judge."},
   {year: "A.D. 16", description: "Lachoneus receives a threatening letter from Giddianhi and prepares his people to defend against the Gadianton robbers."},
   {year: "A.D. 26", description: "Lachoneus and other leaders establish peace in the land."},
   {year: "A.D. 30", description: "Lachoneus' son becomes chief judge and is murdered."},
	  {year: "A.D. 31*", description: "Lachoneus dies."}]},
 {name: "Laman2",
  lifespan_start: "88 B.C.",
  lifespan_end: "15 B.C.",
  events: [{year: "88 B.C. *", description: "Laman is born."},
	  {year: "63 B.C.", description: "Laman helps free some of the Nephite prisoners in the city of Gid by getting the Lamanite guards drunk."},
	  {year: "15 B.C. *", description: "Laman dies."}]},
 {name: "Lamoni",
  lifespan_start: "129 B.C.",
  lifespan_end: "54 B.C.",
  events: [{year: "129 B.C. *", description: "Lamoni is born."},
	  {year: "90 B.C.", description: "Lamoni receives Ammon as his servant and sends him to watch the flocks. After being miraculously preserved, Ammon teaches Lamoni the gospel, and he is converted. They then travel to Middoni to free Ammon's brethren. On the way, they meet Lamoni's father, who tries to kill him and Ammon in turn. Ammon withstands Lamoni’s father and compels him to let Lamoni reign unhindered. Ammon and Lamoni proceed to Middoni and free Ammon's brethren."},
   {year: "81 B.C. *", description: "Lamoni meets with Ammon and Anti-Nephi-Lehi to discuss how to preserve the people of Anti-Nephi-Lehi from the Lamanites."},
	  {year: "54 B.C. *", description: "Lamoni dies."}]},
 {name: "Lehi",
  lifespan_start: "644 B.C.",
  lifespan_end: "579 B.C.",
  events: [{year: "644 B.C. *", description: "Lehi is born."},
   {year: "597 B.C.", description: "Lehi preaches in Jerusalem. After his life is threatened, he and his family depart into the wilderness."},
   {year: "596-588 B.C.", description: "Lehi sends his sons back to get the brass plates, then again to bring Ishmael's family into the wilderness."},
   {year: "595 B.C. *", description: "Lehi has a vision of the Tree of Life."},
   {year: "588 B.C.", description: "Lehi's family arrives in the land Bountiful, and Nephi begins building the ship."},
   {year: "588 B.C.", description: "Lehi and his family set sail for the promised land."},
   {year: "587-586 B.C.", description: "Lehi's family arrives in the promised land."},
   {year: "585 B.C. ", description: "Lehi blesses his children."},
   {year: "584 B.C. *", description: "Lehi dies."}]},
 {name: "Limhi",
  lifespan_start: "159 B.C.",
  lifespan_end: "79 B.C.",
  events: [{year: "159 B.C. *", description: "Limhi is born."},
	  {year: "144 B.C.", description: "Limhi's father, King Noah, suffers death by fire. The Lamanites blame Limhi's people for kidnapping their daughters, and Limhi pacifies them."},
   {year: "123 B.C. *", description: "Limhi sends 43 of his people to look for the land of Zarahemla. They find the remains of the Jaredites instead and bring back the 24 Jaredite plates."},
   {year: "121 B.C.", description: "Limhi receives Ammon the Mulekite and his brethren and is converted to the gospel. He tells Ammon about the 24 Jaredite plates. Limhi and his people escape from Lamanite bondage and become subjects of King Mosiah."},
	  {year: "79 B.C. *", description: "Limhi dies."}]},
 {name: "Mormon",
  lifespan_start: "A.D. 312",
  lifespan_end: "A.D. 391",
  events: [{year: "A.D. 312", description: "Mormon is born."},
   {year: "A.D. 322", description: "Ammaron instructs Mormon concerning the sacred records."},
   {year: "A.D. 327", description: "Mormon is visited of the Lord."},
   {year: "A.D. 328", description: "Mormon takes command of the Nephite armies."},
   {year: "A.D. 332", description: "Mormon defeats a Lamanite army of 44,000."},
   {year: "A.D. 337 *", description: "Mormon retrieves the plates of Nephi and begins his abridgment."},
   {year: "A.D. 345", description: "Mormon leads in a battle where thousands are killed in open rebellion."},
   {year: "A.D. 347", description: "Mormon leads a defense against another Lamanite attack."},
   {year: "A.D. 351", description: "The Nephites and Lamanites enter into a treaty to divide their lands."},
   {year: "A.D. 361", description: "Mormon leads another defense against yet another Lamanite attack."},
   {year: "A.D. 362", description: "Mormon defends the city of Desolation against the Lamanites."},
   {year: "A.D. 363", description: "Mormon refuses to lead the Nephite armies because of their wickedness."},
   {year: "A.D. 375", description: "The Lamanites come against the Nephites with all their forces. Mormon retrieves all of the sacred records and agrees to command the Nephite armies again."},
   {year: "A.D. 385", description: "The Nephites make their last stand at Cumorah. All are killed except for Mormon, Moroni, and twenty-two others."},
   {year: "A.D. 391 *", description: "Mormon dies."}]},
 {name: "Moroni",
  lifespan_start: "A.D. 341",
  lifespan_end: "A.D. 426",
  events: [{year: "A.D. 341 *", description: "Moroni is born."},
   {year: "A.D. 385", description: "Moroni leads an army of 10,000 at Cumorah during the final battle of the Nephites. All the Nephites are killed, except for Mormon, Moroni, and twenty-two others."},
   {year: "A.D. 401", description: "Moroni is the last surviving Nephite."},
   {year: "A.D. 421", description: "Moroni finishes abridging the records and buries the plates in Cumorah."},
   {year: "A.D. 426 *", description: "Moroni dies."}]},
 {name: "Mosiah2",
  lifespan_start: "229 B.C.",
  lifespan_end: "149 B.C.",
  events: [{year: "229 B.C. *", description: "Mosiah is born."},
   {year: "210 B.C. *", description: "Mosiah and his people are warned of the Lord to leave the land of Nephi. They are led through the wilderness to the land of Zarahemla, where they discover the Mulekites. The peoples unite and Mosiah is made their king. He translates a large stone engraved with a Jaredite record."},
   {year: "190 B.C. *", description: "Mosiah's son, Benjamin, is born."},
   {year: "154 B.C.", description: "Mosiah's grandson, Mosiah, is born."},
   {year: "149 B.C. *", description: "Mosiah dies."}]},
 {name: "Mosiah",
  lifespan_start: "154 B.C.",
  lifespan_end: "91 B.C.",
  events: [{year: "154 B.C.", description: "Mosiah is born."},
   {year: "124 B.C.", description: "Mosiah begins to reign as king."},
   {year: "121 B.C.", description: "Mosiah sends Ammon the Mulekite to search for the people of Zeniff."},
   {year: "120 B.C.", description: "The Nephites, Mulekites, and people of Alma and Limhi unite to become Nephites. Mosiah gives Alma authority to establish the Church of God."},
   {year: "92 B.C.", description: "Mosiah translates the Jaredite record."},
   {year: "91 B.C.", description: "Mosiah establishes the reign of the judges and dies."}]},
 {name: "Nephi",
  lifespan_start: "614 B.C.",
  lifespan_end: "539 B.C.",
  events: [{year: "614 B.C. *", description: "Nephi is born."},
   {year: "597 B.C.", description: "Lehi's family departs into the wilderness."},
   {year: "596-588 B.C.", description: "Nephi and his brothers return to Jerusalem for the brass plates, and then again for Ishmael's family. They marry Ishmael's daughters. Laman and Lemuel murmur repeatedly, and are in turn chastened repeatedly."},
   {year: "588 B.C.", description: "Nephi's family arrives in the land Bountiful, and Nephi begins building the ship."},
   {year: "587-586 B.C.", description: "Lehi's family arrives in the promised land. Sometime during the voyage, Laman and Lemuel bind Nephi and steer the ship into a tempest."},
   {year: "585 B.C. *", description: "Nephi and his brothers receive their final blessings from Lehi."},
   {year: "584 B.C. *", description: "Lehi dies. Nephi, Sam, Jacob, Joseph, and Nephi's followers separate from Laman and Lemuel."},
   {year: "544 B.C.", description: "Nephi gives the small plates to Jacob."},
   {year: "539 B.C. *", description: "Nephi dies."}]},
 {name: "Nephi2",
  lifespan_start: "50 B.C.",
  lifespan_end: "A.D. 12",
  events: [{year: "50 B.C. *", description: "Nephi is born."},
   {year: "39 B.C.", description: "Nephi takes the judgment-seat as chief judge."},
   {year: "30 B.C.", description: "Nephi gives the judgment seat to Cezoram to dedicate all his time to the ministry. He and his brother Lehi preach to the Lamanites, the majority of whom become converted to the gospel."},
   {year: "23 B.C.", description: "Nephi prophetically reveals the murder of Seezoram, the chief judge. Nephi is given the sealing power by the Lord."},
   {year: "19 B.C.", description: "Nephi asks the Lord to cause a famine to come upon the land."},
   {year: "16 B.C.", description: "Nephi asks the Lord to end the famine."},
   {year: "14 B.C. *", description: "Nephi's son, Nephi, is born."},
   {year: "6 B.C.", description: "Nephi baptizes those who believe Samuel's preaching."},
   {year: "A.D. 1", description: "Nephi gives the records to his son, Nephi, and departs out of the land."}]},
 {name: "Nephi3",
   lifespan_start: "14 B.C.",
   lifespan_end: "A.D. 56",
   events: [{year: "14 B.C. *", description: "Nephi is born."},
    {year: "A.D. 1", description: "Nephi receives the records from his father."},
    {year: "A.D. 31-33", description: "Nephi ministers to the people and performs miracles, but few are converted."},
    {year: "A.D. 34", description: "Nephi is chosen as a disciple of the Lord, Jesus Christ, to the Nephites."},
    {year: "A.D. 56 *", description: "Nephi, son of Nephi, dies."}]},
 {name: "Nephihah",
  lifespan_start: "147 B.C.",
  lifespan_end: "67 B.C.",
  events: [{year: "147 B.C. *", description: "Nephihah is born."},
	  {year: "83 B.C.", description: "Nephihah is appointed by Alma to fill the judgment-seat."},
   {year: "67 B.C.", description: "Nephihah dies and his son, Pahoran, takes the judgment-seat."}]},
 {name: "Noah",
  lifespan_start: "187 B.C.",
  lifespan_end: "144 B.C.",
  events: [{year: "187 B.C. *", description: "Noah is born."},
	  {year: "160 B.C.", description: "Zeniff confers the kingdom on his son, Noah."},
   {year: "160-151 B.C.", description: "Noah taxes the people, replaces the priests, and builds many elegant and spacious buildings."},
   {year: "150 B.C.", description: "The Lamanites attack. Noah sends guards, but they are killed. He then sends a small army, which defeats the Lamanites. They become prideful. Abinadi prophesies against Noah and his people."},
   {year: "148 B.C.", description: "Abinadi returns and is captured. After hearing Abinadi's testimony in court, Noah sentences him to death by fire."},
   {year: "145 B.C.", description: "Noah sends his army after the people of Alma."},
   {year: "144 B.C.", description: "Gideon attempts to kill Noah. The Lamanites attack, and the men of the city flee. King Noah is killed by fire."}]},
 {name: "Omni",
  lifespan_start: "389 B.C.",
  lifespan_end: "309 B.C.",
  events: [{year: "389 B.C. *", description: "Omni is born."},
   {year: "360 B.C. *", description: "Omni receives the plates from Jarom."},
   {year: "322 B.C. *", description: "Omni begins his record."},
   {year: "317 B.C.", description: "Omni gives the plates to Amaron."},
   {year: "309 B.C. *", description: "Omni dies."}]},
 {name: "Pahoran",
  lifespan_start: "124 B.C.",
  lifespan_end: "51 B.C.",
  events: [{year: "124 B.C.", description: "Pahoran is born."},
   {year: "68 B.C.", description: "Pahoran is appointed chief judge after his father, Nephihah, dies."},
   {year: "67 B.C.", description: "The king-men attempt to dethrone Pahoran and establish a king over the Nephites."},
   {year: "62 B.C.", description: "Pahoran and Captain Moroni exchange epistles, and Moroni assists Pahoran in quelling the rebellion led by Pachus."},
   {year: "52 B.C.", description: "Pahoran dies. His son, Pahoran II, takes the judgment-seat and is murdered."}]},
 {name: "SamuelLamanite",
  lifespan_start: "25 B.C. *",
  lifespan_end: "A.D. 55 *",
  events: [{year: "25 B.C. *", description: "Samuel is born."},
	  {year: "5 B.C.", description: "Samuel prophesies the Nephites' destruction unless they repent. He predicts signs of Christ's birth and death. He is miraculously preserved while on the city wall, and goes to preach to his own people."},
	  {year: "A.D. 55 *", description: "Samuel dies."}]},
 {name: "Sariah",
  lifespan_start: "640 B.C.",
  lifespan_end: "570 B.C.",
  events: [{year: "640 B.C. *", description: "Sariah is born."},
	  {year: "597 B.C.", description: "Sariah leaves with Lehi into the wilderness after his life is threatened."},
   {year: "595 B.C. *", description: "Sariah complains against Lehi out of fear for her sons, and Lehi comforts her."},
   {year: "588 B.C.", description: "Lehi's family arrives in Bountiful."},
   {year: "588 B.C.", description: "Lehi's family sets sail for the promised land."},
   {year: "587-586 B.C. *", description: "Lehi's family arrives in the promised land."},
	  {year: "570 B.C. *", description: "Sariah dies."}]},
 {name: "Sherem",
  lifespan_start: "586 B.C.",
  lifespan_end: "529 B.C.",
  events: [{year: "586 B.C. *", description: "Sherem is born."},
	  {year: "529 B.C. *", description: "Sherem preaches that there will be no Christ. He contends with Jacob and asks for a sign. As a sign, God smites him. Sherem confesses his sins to the people and God, and dies."}]},
 {name: "Zeezrom",
  lifespan_start: "141 B.C.",
  lifespan_end: "66 B.C.",
  events: [{year: "141 B.C. *", description: "Zeezrom is born."},
	  {year: "82 B.C.", description: "Zeezrom contends with Alma and Amulek in the city of Ammonihah. He repents and is cast of the city."},
   {year: "81 B.C.", description: "Alma and Amulek heal Zeezrom of a fever."},
   {year: "74 B.C.", description: "Zeezrom accompanies Alma and others on a mission to the Zoramites."},
	  {year: "66 B.C. *", description: "Zeezrom dies."}]},
 {name: "Zeniff",
  lifespan_start: "214 B.C.",
  lifespan_end: "159 B.C.",
  events: [{year: "214 B.C. *", description: "Zeniff is born."},
	  {year: "200-175 B.C.", description: "Zeniff and his people return to the land of Lehi-Nephi."},
   {year: "187 B.C.", description: "A war is fought between the Lamanites and Zeniff's people."},
   {year: "178 B.C.", description: "The Lamanites attack the people of Zeniff. Zeniff’s people defeat them and return to their own lands."},
   {year: "160 B.C.", description: "Zeniff confers the kingdom on his son, Noah."},
	  {year: "159 B.C. *", description: "Zeniff dies."}]},
 {name: "Zerahemnah",
  lifespan_start: "123 B.C.",
  lifespan_end: "74 B.C.",
  events: [{year: "123 B.C. *", description: "Zerahemnah is born."},
	  {year: "74 B.C.", description: "Zerahemnah leads an attack against the Nephites and fights until his armies are surrounded. Moroni demands that they drop their weapons and covenant not to come to war anymore. Zerahemnah refuses to make a covenant that he will not keep. He attacks Moroni and is scalped by a soldier. The fight continues until Zerahemnah surrenders and agrees to make the covenant."}]}]
